# docker-compose.yml - Only for local debug purposes

version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: local-postgres
    environment:
      TZ: UTC
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
      # get ip address for connect to pgadmin
      # docker inspect loc-postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: local-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  mysql:
    image: mysql:5.7
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql_data/db:/var/lib/mysql

  mongo:
    image: mongo:5.0
    container_name: local-mongo
    environment:
      TZ: UTC
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - '27017:27017'
    volumes:
      - ./.mongo_data:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: local-redis
    environment:
      TZ: UTC
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456
      REDIS_HOST: cache
      #REDIS_USERNAME: default
    command: ["redis-server", "--appendonly", "yes", "--requirepass","123456"]
    ports:
      - '6379:6379'
    volumes:
      - ./.redis_data:/data

  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: local-camunda
    environment:
      TZ: UTC
    ports:
      - "8443:8080"

  jaeger:
    container_name: local-jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - LOG_LEVEL=debug

  app:
    container_name: local-app
    env_file:
      - .env
      #- .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    command: "yarn start"
    ports:
      - '8080:8080'
    networks:
      - nestjs-network
    volumes:
      - ./usr/src/app
      - ./usr/src/app/node_modules
    restart: unless-stopped

networks:
  nestjs-network:

  #zookeeper:
  #  container_name: loc-zookeeper
  #  logging:
  #    driver: none
  #  image: wurstmeister/zookeeper:latest
  #  environment:
  #    ZOOKEEPER_CLIENT_PORT: 2181
  #  ports:
  #    - "2181:2181"

  #kafka:
  #  container_name: loc-kafka
  #  image: wurstmeister/kafka:2.12-2.3.0
  #  logging:
  #    driver: none
  #  environment:
  #    KAFKA_ADVERTISED_LISTENERS: >-
  #      LISTENER_DOCKER_INTERNAL://kafka:19092,
  #      LISTENER_DOCKER_EXTERNAL://kafka:9092
  #    KAFKA_LISTENERS: >-
  #      LISTENER_DOCKER_INTERNAL://:19092,
  #      LISTENER_DOCKER_EXTERNAL://:9092
  #    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
  #      LISTENER_DOCKER_INTERNAL:PLAINTEXT,
  #      LISTENER_DOCKER_EXTERNAL:PLAINTEXT
  #    KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #    KAFKA_CREATE_TOPICS: "prisma.sampleApi.topic.v1:1:1"
  #    KAFKA_LOG4J_LOGGERS: >-
  #      kafka.controller=INFO,
  #      kafka.producer.async.DefaultEventHandler=INFO,
  #      state.change.logger=INFO
  #  ports:
  #    - '9092:9092'
  #  depends_on:
  #    - zookeeper
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
